name: Visitor Counter

on:
  workflow_dispatch: # allow manual trigger
  repository_dispatch:
    types: [visit]

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Increment counter
        run: |
          count=$(jq ".visits + 1" counter.json)
          echo "{ \"visits\": $count }" > counter.json

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add counter.json
          git commit -m "Increment counter"
          git push
